### ISSUE TITLE
Wrong internal link on document

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeDocs/cc-everywhere#114]
### Expected Behaviour
Link goes to appropriate sections
### Actual Behaviour
Link goes to Callback sections

https://github.com/AdobeDocs/cc-everywhere/blob/5dfbfcafae076a68081a9ab3fabda620b0859be1/src/pages/reference/CCEverywhere/create_design/index.md?plain=1#L42

https://github.com/AdobeDocs/cc-everywhere/blob/5dfbfcafae076a68081a9ab3fabda620b0859be1/src/pages/reference/CCEverywhere/create_design/index.md?plain=1#L44

**Comment by amandahuarng** [comment]
Fixed.
