### ISSUE TITLE
In Adobe Embed SDK Get Credentials workflow, the "Next Steps" button is leading to an invalid path

### ISSUE THREAD

**Issue by sgera** [AdobeDocs/cc-everywhere#115]
In Adobe Embed SDK’s [Get Credentials workflow](https://developer.adobe.com/express/embed-sdk/docs/get-credential/), the `Next Steps` button is leading to an [invalid path](https://developer.adobe.com/credentials/nextsteps) (HTTP 404)

### Expected Behaviour
It should take to a valid documentation page. I am not sure what the right page is.

### Actual Behaviour
![image](https://github.com/AdobeDocs/cc-everywhere/assets/5928555/13a568b8-84ad-4088-854b-f38d730c00fb)

#### Steps to Reproduce
1. Go to https://developer.adobe.com/express/embed-sdk/docs/get-credential/ and login using your Adobe id
2. Create a credential (enter name, domain etc.)
3. Once the credential is created, click on `Next Steps` button 

![Screenshot 2023-10-13 at 12 34 26 PM](https://github.com/AdobeDocs/cc-everywhere/assets/5928555/95b2f116-8a3e-4c87-a8fa-25b98523a75d)

**Comment by amandahuarng** [comment]
Hi @sgera --

Thanks for your feedback. The team has fixed the link on that button and it points to the quickstart guide now: https://developer.adobe.com/express/embed-sdk/docs/guides/quickstart/

Best, 
Amanda
